package profilemanagement.frontend;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;


public class AllFriendsPanel extends javax.swing.JPanel {

    
    public AllFriendsPanel(ArrayList<FriendsPanel> fps) {
        initComponents();
        setPreferredSize(new Dimension(240, 600));
        //friendListContainerPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        friendListContainerPanel.setLayout(new javax.swing.BoxLayout(friendListContainerPanel, javax.swing.BoxLayout.Y_AXIS));
        addPanel(fps);
    }
    
    public void addPanel(ArrayList<FriendsPanel> fps) {
        for (FriendsPanel fp : fps)
            friendListContainerPanel.add(fp);
    }
    
    public static void main(String[] args) {
        // Sample data
        String[][] users = {
            {"Youssef Keshk", "src\\main\\java\\resources\\image.jpeg", "offline"},
            {"Zeyad Essam", "src\\main\\java\\resources\\image1.jpg", "online"},
            {"Ibrahim Sayed", "src\\main\\java\\resources\\image1.2.jpg", "online"},
            {"Ali Mohamed", "src\\main\\java\\resources\\profilePic.png", "online"},
            {"Ezz Mazen", "src\\main\\java\\resources\\profilePic.png", "offline"},
            {"Ahmed Ali", "src\\main\\java\\resources\\image1.jpg", "offline"},
            {"Mohamed Zain", "src\\main\\java\\resources\\image1.2.jpg", "offline"},
            {"Yassin Wael", "src\\main\\java\\resources\\profilePic.png", "online"},
            {"Ali Mohamed", "src\\main\\java\\resources\\profilePic.png", "online"},
            {"Ezz Mazen", "src\\main\\java\\resources\\profilePic.png", "offline"},
            {"Ahmed Ali", "src\\main\\java\\resources\\image1.jpg", "offline"},
            {"Mohamed Zain", "src\\main\\java\\resources\\image1.2.jpg", "offline"},
            {"Yassin Wael", "src\\main\\java\\resources\\profilePic.png", "online"},
            {"Ali Mohamed", "src\\main\\java\\resources\\profilePic.png", "online"},
            {"Ezz Mazen", "src\\main\\java\\resources\\profilePic.png", "offline"},
            {"Ahmed Ali", "src\\main\\java\\resources\\image1.jpg", "offline"},
            {"Mohamed Zain", "src\\main\\java\\resources\\image1.2.jpg", "offline"},
            {"Yassin Wael", "src\\main\\java\\resources\\profilePic.png", "online"}
        };
        
        ArrayList<FriendsPanel> fps = new ArrayList<>();
        for(String[] user: users) {
            fps.add(new FriendsPanel(user[0], user[1], user[2]));
        }
        
        AllFriendsPanel asfp = new AllFriendsPanel(fps);
        
        JFrame frame = new JFrame("Friend List");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(asfp);
        frame.pack();
        frame.setVisible(true);

    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(240, 600); // Width and height for the panel
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendListContainerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Friends");
        titleLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(titleLabel, java.awt.BorderLayout.PAGE_START);

        friendListContainerPanel.setLayout(new javax.swing.BoxLayout(friendListContainerPanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(friendListContainerPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel friendListContainerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
