package friendmanagement.frontend;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;


public class SuggestedFriendsPanel extends javax.swing.JPanel {

 
    public SuggestedFriendsPanel() {
        initComponents();
        setPreferredSize(new Dimension(240, 600));
        setMinimumSize(new Dimension(220, 600));
        suggestionListContainerPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        suggestionListContainerPanel.setLayout(new javax.swing.BoxLayout(suggestionListContainerPanel, javax.swing.BoxLayout.Y_AXIS));

    }
    
    public void addPanel(JPanel suggestionItem) {
        suggestionListContainerPanel.add(suggestionItem);
    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(240, 600); // Width and height for the panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        suggestionsScrollPane = new javax.swing.JScrollPane();
        suggestionListContainerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Friend Suggestions");
        titleLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titleLabel.setMaximumSize(new java.awt.Dimension(240, 21));
        titleLabel.setMinimumSize(new java.awt.Dimension(220, 21));
        titleLabel.setPreferredSize(new java.awt.Dimension(220, 21));
        add(titleLabel, java.awt.BorderLayout.PAGE_START);

        suggestionListContainerPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("MenuBar.hoverBackground"));
        suggestionListContainerPanel.setLayout(new javax.swing.BoxLayout(suggestionListContainerPanel, javax.swing.BoxLayout.LINE_AXIS));

        suggestionListContainerPanel.setLayout(new javax.swing.BoxLayout(suggestionListContainerPanel, javax.swing.BoxLayout.Y_AXIS));

        suggestionsScrollPane.setViewportView(suggestionListContainerPanel);

        add(suggestionsScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel suggestionListContainerPanel;
    private javax.swing.JScrollPane suggestionsScrollPane;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
        SuggestedFriendsPanel asfp = new SuggestedFriendsPanel();
        

        // Sample data
        String[][] sampleUsers = {
            {"Youssef Keshk", "src\\main\\java\\resources\\image.jpeg"},
            {"Zeyad Essam", "src\\main\\java\\resources\\image1.jpg"},
            {"Ibrahim Sayed", "src\\main\\java\\resources\\image1.2.jpg"},
            {"Ali Mohamed", "src\\main\\java\\resources\\profilePic.png"},
             {"Youssef Keshk", "src\\main\\java\\resources\\image.jpeg"},
            {"Zeyad Essam", "src\\main\\java\\resources\\image1.jpg"},
            {"Ibrahim Sayed", "src\\main\\java\\resources\\image1.2.jpg"},
            {"Ali Mohamed", "src\\main\\java\\resources\\profilePic.png"},
            {"Ezz Mazen", "src\\main\\java\\resources\\profilePic.png"}
        };
        for (String[] user : sampleUsers) {
            JPanel suggestionItem = new UserSuggestedFriendsPanel(user[0], user[1]);
            asfp.addPanel(suggestionItem);
        }
        
        JFrame frame = new JFrame("Friend Suggestions");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(asfp);
        frame.pack();
        frame.setVisible(true);
    }
}


