package contentcreation.frontend;

import java.awt.Dimension;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JFrame;


public class ContentPanel extends javax.swing.JPanel {

    
    public ContentPanel(UserStoryCarouselPanel scp, ArrayList<UserContentPanel> cps) {
        initComponents();
        setPreferredSize(new Dimension(460, 600));
        //contentPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.Y_AXIS));
        addPanel(scp, cps);
    }
    
    public void addPanel(UserStoryCarouselPanel scp, ArrayList<UserContentPanel> cps) {
        contentPanel.add(scp);
        for(UserContentPanel c : cps)
            contentPanel.add(c);
    }
    
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(460,600); // Width and height for the panel
        
    }
    
    
    public static void main(String[] args) {
        //// Testing
        UserContentPanel cp1 = new UserContentPanel("Youssef Keshk",
                "src/main/java/resources/profilePic.png",
                "src/main/java/resources/image.jpeg",
                LocalDateTime.now(),
                "Good morning everyone!!");

        UserContentPanel cp2 = new UserContentPanel("Zeyad Essam",
                "src\\main\\java\\resources\\image.jpeg",
                "src\\main\\java\\resources\\profilePic.png",
                LocalDateTime.now(),
                "Sunny day, innit!!!");
        
        UserContentPanel cp3 = new UserContentPanel("Ibrahim Sayed",
                "src\\main\\java\\resources\\profilePic.png",
                "src\\main\\java\\resources\\image1.jpg",
                LocalDateTime.now(),
                "Hello everyone. hope your okay.");
        UserContentPanel cp4 = new UserContentPanel("Youssef Keshk",
                "src\\main\\java\\resources\\profilePic.png",
                "src\\main\\java\\resources\\image.jpeg",
                LocalDateTime.now(),
                "Good morning everyone!!");

        UserContentPanel cp5 = new UserContentPanel("Zeyad Essam",
                "src\\main\\java\\resources\\image.jpeg",
                "src\\main\\java\\resources\\profilePic.png",
                LocalDateTime.now(),
                "Sunny day, innit!!!");
        
        UserContentPanel cp6 = new UserContentPanel("Ibrahim Sayed",
                "src\\main\\java\\resources\\profilePic.png",
                "src\\main\\java\\resources\\image1.jpg",
                LocalDateTime.now(),
                "Hello everyone. hope your okay.");

        ArrayList<UserContentPanel> cps = new ArrayList<>();
        ArrayList<UserContentPanel> cps2 = new ArrayList<>();
        cps.add(cp1);cps2.add(cp4);
        cps.add(cp2);cps2.add(cp5);
        cps.add(cp3);cps2.add(cp6);
        
        

        UserStoryCarouselPanel scp = new UserStoryCarouselPanel(cps);
        
        ContentPanel allcontent = new ContentPanel(scp, cps2);

        JFrame frame = new JFrame("All content");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(allcontent);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(contentPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
